var annotated_dup =
[
    [ "gemmi", "namespacegemmi.html", [
      [ "cif", "namespacegemmi_1_1cif.html", [
        [ "rules", "namespacegemmi_1_1cif_1_1rules.html", [
          [ "lookup_char", "structgemmi_1_1cif_1_1rules_1_1lookup__char.html", "structgemmi_1_1cif_1_1rules_1_1lookup__char" ],
          [ "nonblank_ch", "structgemmi_1_1cif_1_1rules_1_1nonblank__ch.html", null ],
          [ "anyprint_ch", "structgemmi_1_1cif_1_1rules_1_1anyprint__ch.html", null ],
          [ "comment", "structgemmi_1_1cif_1_1rules_1_1comment.html", null ],
          [ "whitespace", "structgemmi_1_1cif_1_1rules_1_1whitespace.html", null ],
          [ "ws_or_eof", "structgemmi_1_1cif_1_1rules_1_1ws__or__eof.html", null ],
          [ "str_data", "structgemmi_1_1cif_1_1rules_1_1str__data.html", null ],
          [ "str_loop", "structgemmi_1_1cif_1_1rules_1_1str__loop.html", null ],
          [ "str_global", "structgemmi_1_1cif_1_1rules_1_1str__global.html", null ],
          [ "str_save", "structgemmi_1_1cif_1_1rules_1_1str__save.html", null ],
          [ "str_stop", "structgemmi_1_1cif_1_1rules_1_1str__stop.html", null ],
          [ "keyword", "structgemmi_1_1cif_1_1rules_1_1keyword.html", null ],
          [ "endq", "structgemmi_1_1cif_1_1rules_1_1endq.html", null ],
          [ "quoted_tail", "structgemmi_1_1cif_1_1rules_1_1quoted__tail.html", null ],
          [ "quoted", "structgemmi_1_1cif_1_1rules_1_1quoted.html", null ],
          [ "singlequoted", "structgemmi_1_1cif_1_1rules_1_1singlequoted.html", null ],
          [ "doublequoted", "structgemmi_1_1cif_1_1rules_1_1doublequoted.html", null ],
          [ "field_sep", "structgemmi_1_1cif_1_1rules_1_1field__sep.html", null ],
          [ "textfield", "structgemmi_1_1cif_1_1rules_1_1textfield.html", null ],
          [ "unquoted", "structgemmi_1_1cif_1_1rules_1_1unquoted.html", null ],
          [ "datablockname", "structgemmi_1_1cif_1_1rules_1_1datablockname.html", null ],
          [ "datablockheading", "structgemmi_1_1cif_1_1rules_1_1datablockheading.html", null ],
          [ "tag", "structgemmi_1_1cif_1_1rules_1_1tag.html", null ],
          [ "simunq", "structgemmi_1_1cif_1_1rules_1_1simunq.html", null ],
          [ "value", "structgemmi_1_1cif_1_1rules_1_1value.html", null ],
          [ "item_tag", "structgemmi_1_1cif_1_1rules_1_1item__tag.html", null ],
          [ "item_value", "structgemmi_1_1cif_1_1rules_1_1item__value.html", null ],
          [ "loop_tag", "structgemmi_1_1cif_1_1rules_1_1loop__tag.html", null ],
          [ "loop_value", "structgemmi_1_1cif_1_1rules_1_1loop__value.html", null ],
          [ "loop_end", "structgemmi_1_1cif_1_1rules_1_1loop__end.html", null ],
          [ "loop", "structgemmi_1_1cif_1_1rules_1_1loop.html", null ],
          [ "missing_value", "structgemmi_1_1cif_1_1rules_1_1missing__value.html", null ],
          [ "dataitem", "structgemmi_1_1cif_1_1rules_1_1dataitem.html", null ],
          [ "framename", "structgemmi_1_1cif_1_1rules_1_1framename.html", null ],
          [ "endframe", "structgemmi_1_1cif_1_1rules_1_1endframe.html", null ],
          [ "frame", "structgemmi_1_1cif_1_1rules_1_1frame.html", null ],
          [ "datablock", "structgemmi_1_1cif_1_1rules_1_1datablock.html", null ],
          [ "content", "structgemmi_1_1cif_1_1rules_1_1content.html", null ],
          [ "file", "structgemmi_1_1cif_1_1rules_1_1file.html", null ],
          [ "one_block", "structgemmi_1_1cif_1_1rules_1_1one__block.html", null ]
        ] ],
        [ "Action", "structgemmi_1_1cif_1_1Action.html", null ],
        [ "Action< rules::datablockname >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1datablockname_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1datablockname_01_4" ],
        [ "Action< rules::str_global >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1str__global_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1str__global_01_4" ],
        [ "Action< rules::framename >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1framename_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1framename_01_4" ],
        [ "Action< rules::endframe >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1endframe_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1endframe_01_4" ],
        [ "Action< rules::item_tag >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1item__tag_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1item__tag_01_4" ],
        [ "Action< rules::item_value >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1item__value_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1item__value_01_4" ],
        [ "Action< rules::str_loop >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1str__loop_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1str__loop_01_4" ],
        [ "Action< rules::loop_tag >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1loop__tag_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1loop__tag_01_4" ],
        [ "Action< rules::loop_value >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1loop__value_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1loop__value_01_4" ],
        [ "Action< rules::loop >", "structgemmi_1_1cif_1_1Action_3_01rules_1_1loop_01_4.html", "structgemmi_1_1cif_1_1Action_3_01rules_1_1loop_01_4" ],
        [ "CheckAction", "structgemmi_1_1cif_1_1CheckAction.html", null ],
        [ "CheckAction< rules::missing_value >", "structgemmi_1_1cif_1_1CheckAction_3_01rules_1_1missing__value_01_4.html", "structgemmi_1_1cif_1_1CheckAction_3_01rules_1_1missing__value_01_4" ],
        [ "LoopArg", "structgemmi_1_1cif_1_1LoopArg.html", null ],
        [ "FrameArg", "structgemmi_1_1cif_1_1FrameArg.html", "structgemmi_1_1cif_1_1FrameArg" ],
        [ "CommentArg", "structgemmi_1_1cif_1_1CommentArg.html", "structgemmi_1_1cif_1_1CommentArg" ],
        [ "Loop", "structgemmi_1_1cif_1_1Loop.html", "structgemmi_1_1cif_1_1Loop" ],
        [ "Column", "classgemmi_1_1cif_1_1Column.html", "classgemmi_1_1cif_1_1Column" ],
        [ "Table", "structgemmi_1_1cif_1_1Table.html", "structgemmi_1_1cif_1_1Table" ],
        [ "Block", "structgemmi_1_1cif_1_1Block.html", "structgemmi_1_1cif_1_1Block" ],
        [ "Item", "structgemmi_1_1cif_1_1Item.html", "structgemmi_1_1cif_1_1Item" ],
        [ "ItemSpan", "structgemmi_1_1cif_1_1ItemSpan.html", "structgemmi_1_1cif_1_1ItemSpan" ],
        [ "Document", "structgemmi_1_1cif_1_1Document.html", "structgemmi_1_1cif_1_1Document" ],
        [ "Ddl", "structgemmi_1_1cif_1_1Ddl.html", "structgemmi_1_1cif_1_1Ddl" ],
        [ "WriteOptions", "structgemmi_1_1cif_1_1WriteOptions.html", "structgemmi_1_1cif_1_1WriteOptions" ],
        [ "BufOstream", "classgemmi_1_1cif_1_1BufOstream.html", "classgemmi_1_1cif_1_1BufOstream" ],
        [ "JsonWriteOptions", "structgemmi_1_1cif_1_1JsonWriteOptions.html", "structgemmi_1_1cif_1_1JsonWriteOptions" ]
      ] ],
      [ "impl", "namespacegemmi_1_1impl.html", [
        [ "GridConstPoint", "structgemmi_1_1impl_1_1GridConstPoint.html", "structgemmi_1_1impl_1_1GridConstPoint" ],
        [ "IsMmCifFile", "structgemmi_1_1impl_1_1IsMmCifFile.html", "structgemmi_1_1impl_1_1IsMmCifFile" ],
        [ "IsCifFile", "structgemmi_1_1impl_1_1IsCifFile.html", "structgemmi_1_1impl_1_1IsCifFile" ],
        [ "IsPdbFile", "structgemmi_1_1impl_1_1IsPdbFile.html", "structgemmi_1_1impl_1_1IsPdbFile" ],
        [ "IsCoordinateFile", "structgemmi_1_1impl_1_1IsCoordinateFile.html", "structgemmi_1_1impl_1_1IsCoordinateFile" ],
        [ "IsAnyFile", "structgemmi_1_1impl_1_1IsAnyFile.html", "structgemmi_1_1impl_1_1IsAnyFile" ],
        [ "IsMatchingFile", "structgemmi_1_1impl_1_1IsMatchingFile.html", "structgemmi_1_1impl_1_1IsMatchingFile" ],
        [ "TwoFoldData", "structgemmi_1_1impl_1_1TwoFoldData.html", "structgemmi_1_1impl_1_1TwoFoldData" ],
        [ "TwoFold_", "structgemmi_1_1impl_1_1TwoFold__.html", "structgemmi_1_1impl_1_1TwoFold__" ]
      ] ],
      [ "psimpl", "namespacegemmi_1_1psimpl.html", [
        [ "Node", "structgemmi_1_1psimpl_1_1Node.html", "structgemmi_1_1psimpl_1_1Node" ],
        [ "AndNode", "structgemmi_1_1psimpl_1_1AndNode.html", "structgemmi_1_1psimpl_1_1AndNode" ],
        [ "OrNode", "structgemmi_1_1psimpl_1_1OrNode.html", "structgemmi_1_1psimpl_1_1OrNode" ],
        [ "NotNode", "structgemmi_1_1psimpl_1_1NotNode.html", "structgemmi_1_1psimpl_1_1NotNode" ],
        [ "GlobMatchNode", "structgemmi_1_1psimpl_1_1GlobMatchNode.html", "structgemmi_1_1psimpl_1_1GlobMatchNode" ],
        [ "AltLocNode", "structgemmi_1_1psimpl_1_1AltLocNode.html", "structgemmi_1_1psimpl_1_1AltLocNode" ],
        [ "ResiRangeNode", "structgemmi_1_1psimpl_1_1ResiRangeNode.html", "structgemmi_1_1psimpl_1_1ResiRangeNode" ],
        [ "IndexRangeNode", "structgemmi_1_1psimpl_1_1IndexRangeNode.html", "structgemmi_1_1psimpl_1_1IndexRangeNode" ],
        [ "ElementNode", "structgemmi_1_1psimpl_1_1ElementNode.html", "structgemmi_1_1psimpl_1_1ElementNode" ],
        [ "HetatmNode", "structgemmi_1_1psimpl_1_1HetatmNode.html", "structgemmi_1_1psimpl_1_1HetatmNode" ],
        [ "EntityTypeNode", "structgemmi_1_1psimpl_1_1EntityTypeNode.html", "structgemmi_1_1psimpl_1_1EntityTypeNode" ],
        [ "HydrogenNode", "structgemmi_1_1psimpl_1_1HydrogenNode.html", "structgemmi_1_1psimpl_1_1HydrogenNode" ],
        [ "BfactorNode", "structgemmi_1_1psimpl_1_1BfactorNode.html", "structgemmi_1_1psimpl_1_1BfactorNode" ],
        [ "OccupancyNode", "structgemmi_1_1psimpl_1_1OccupancyNode.html", "structgemmi_1_1psimpl_1_1OccupancyNode" ],
        [ "BackboneNode", "structgemmi_1_1psimpl_1_1BackboneNode.html", "structgemmi_1_1psimpl_1_1BackboneNode" ],
        [ "SidechainNode", "structgemmi_1_1psimpl_1_1SidechainNode.html", "structgemmi_1_1psimpl_1_1SidechainNode" ],
        [ "AllNode", "structgemmi_1_1psimpl_1_1AllNode.html", "structgemmi_1_1psimpl_1_1AllNode" ],
        [ "State", "structgemmi_1_1psimpl_1_1State.html", "structgemmi_1_1psimpl_1_1State" ],
        [ "ws", "structgemmi_1_1psimpl_1_1ws.html", null ],
        [ "sep", "structgemmi_1_1psimpl_1_1sep.html", null ],
        [ "integer", "structgemmi_1_1psimpl_1_1integer.html", null ],
        [ "float_num", "structgemmi_1_1psimpl_1_1float__num.html", null ],
        [ "wildcard_char", "structgemmi_1_1psimpl_1_1wildcard__char.html", null ],
        [ "identifier", "structgemmi_1_1psimpl_1_1identifier.html", null ],
        [ "atom_name_str", "structgemmi_1_1psimpl_1_1atom__name__str.html", null ],
        [ "element_str", "structgemmi_1_1psimpl_1_1element__str.html", null ],
        [ "op_le", "structgemmi_1_1psimpl_1_1op__le.html", null ],
        [ "op_ge", "structgemmi_1_1psimpl_1_1op__ge.html", null ],
        [ "op_ne", "structgemmi_1_1psimpl_1_1op__ne.html", null ],
        [ "op_lt", "structgemmi_1_1psimpl_1_1op__lt.html", null ],
        [ "op_gt", "structgemmi_1_1psimpl_1_1op__gt.html", null ],
        [ "op_eq", "structgemmi_1_1psimpl_1_1op__eq.html", null ],
        [ "compare_op", "structgemmi_1_1psimpl_1_1compare__op.html", null ],
        [ "kw_chain", "structgemmi_1_1psimpl_1_1kw__chain.html", null ],
        [ "kw_resn", "structgemmi_1_1psimpl_1_1kw__resn.html", null ],
        [ "kw_resi", "structgemmi_1_1psimpl_1_1kw__resi.html", null ],
        [ "kw_name", "structgemmi_1_1psimpl_1_1kw__name.html", null ],
        [ "kw_alt", "structgemmi_1_1psimpl_1_1kw__alt.html", null ],
        [ "kw_elem", "structgemmi_1_1psimpl_1_1kw__elem.html", null ],
        [ "kw_index", "structgemmi_1_1psimpl_1_1kw__index.html", null ],
        [ "kw_id", "structgemmi_1_1psimpl_1_1kw__id.html", null ],
        [ "kw_b", "structgemmi_1_1psimpl_1_1kw__b.html", null ],
        [ "kw_q", "structgemmi_1_1psimpl_1_1kw__q.html", null ],
        [ "kw_and", "structgemmi_1_1psimpl_1_1kw__and.html", null ],
        [ "kw_or", "structgemmi_1_1psimpl_1_1kw__or.html", null ],
        [ "kw_not", "structgemmi_1_1psimpl_1_1kw__not.html", null ],
        [ "kw_hetatm", "structgemmi_1_1psimpl_1_1kw__hetatm.html", null ],
        [ "kw_polymer", "structgemmi_1_1psimpl_1_1kw__polymer.html", null ],
        [ "kw_solvent", "structgemmi_1_1psimpl_1_1kw__solvent.html", null ],
        [ "kw_water", "structgemmi_1_1psimpl_1_1kw__water.html", null ],
        [ "kw_hydrogens", "structgemmi_1_1psimpl_1_1kw__hydrogens.html", null ],
        [ "kw_h_dot", "structgemmi_1_1psimpl_1_1kw__h__dot.html", null ],
        [ "kw_backbone", "structgemmi_1_1psimpl_1_1kw__backbone.html", null ],
        [ "kw_sidechain", "structgemmi_1_1psimpl_1_1kw__sidechain.html", null ],
        [ "kw_all", "structgemmi_1_1psimpl_1_1kw__all.html", null ],
        [ "val_chain_item", "structgemmi_1_1psimpl_1_1val__chain__item.html", null ],
        [ "val_chain_list", "structgemmi_1_1psimpl_1_1val__chain__list.html", null ],
        [ "rule_chain", "structgemmi_1_1psimpl_1_1rule__chain.html", null ],
        [ "val_resn_item", "structgemmi_1_1psimpl_1_1val__resn__item.html", null ],
        [ "val_resn_list", "structgemmi_1_1psimpl_1_1val__resn__list.html", null ],
        [ "rule_resn", "structgemmi_1_1psimpl_1_1rule__resn.html", null ],
        [ "val_name_item", "structgemmi_1_1psimpl_1_1val__name__item.html", null ],
        [ "val_name_list", "structgemmi_1_1psimpl_1_1val__name__list.html", null ],
        [ "rule_name", "structgemmi_1_1psimpl_1_1rule__name.html", null ],
        [ "val_alt", "structgemmi_1_1psimpl_1_1val__alt.html", null ],
        [ "rule_alt", "structgemmi_1_1psimpl_1_1rule__alt.html", null ],
        [ "val_resi_range", "structgemmi_1_1psimpl_1_1val__resi__range.html", null ],
        [ "val_resi_single", "structgemmi_1_1psimpl_1_1val__resi__single.html", null ],
        [ "rule_resi", "structgemmi_1_1psimpl_1_1rule__resi.html", null ],
        [ "val_index_range", "structgemmi_1_1psimpl_1_1val__index__range.html", null ],
        [ "val_index_single", "structgemmi_1_1psimpl_1_1val__index__single.html", null ],
        [ "rule_index", "structgemmi_1_1psimpl_1_1rule__index.html", null ],
        [ "val_elem_item", "structgemmi_1_1psimpl_1_1val__elem__item.html", null ],
        [ "val_elem_list", "structgemmi_1_1psimpl_1_1val__elem__list.html", null ],
        [ "rule_elem", "structgemmi_1_1psimpl_1_1rule__elem.html", null ],
        [ "val_b_compare", "structgemmi_1_1psimpl_1_1val__b__compare.html", null ],
        [ "rule_b", "structgemmi_1_1psimpl_1_1rule__b.html", null ],
        [ "val_q_compare", "structgemmi_1_1psimpl_1_1val__q__compare.html", null ],
        [ "rule_q", "structgemmi_1_1psimpl_1_1rule__q.html", null ],
        [ "rule_hetatm", "structgemmi_1_1psimpl_1_1rule__hetatm.html", null ],
        [ "rule_polymer", "structgemmi_1_1psimpl_1_1rule__polymer.html", null ],
        [ "rule_solvent", "structgemmi_1_1psimpl_1_1rule__solvent.html", null ],
        [ "rule_water", "structgemmi_1_1psimpl_1_1rule__water.html", null ],
        [ "rule_hydrogens", "structgemmi_1_1psimpl_1_1rule__hydrogens.html", null ],
        [ "rule_backbone", "structgemmi_1_1psimpl_1_1rule__backbone.html", null ],
        [ "rule_sidechain", "structgemmi_1_1psimpl_1_1rule__sidechain.html", null ],
        [ "rule_all", "structgemmi_1_1psimpl_1_1rule__all.html", null ],
        [ "property", "structgemmi_1_1psimpl_1_1property.html", null ],
        [ "parens", "structgemmi_1_1psimpl_1_1parens.html", null ],
        [ "not_factor", "structgemmi_1_1psimpl_1_1not__factor.html", null ],
        [ "rule_not", "structgemmi_1_1psimpl_1_1rule__not.html", null ],
        [ "factor", "structgemmi_1_1psimpl_1_1factor.html", null ],
        [ "and_rest", "structgemmi_1_1psimpl_1_1and__rest.html", null ],
        [ "term", "structgemmi_1_1psimpl_1_1term.html", null ],
        [ "or_rest", "structgemmi_1_1psimpl_1_1or__rest.html", null ],
        [ "expression", "structgemmi_1_1psimpl_1_1expression.html", null ],
        [ "grammar", "structgemmi_1_1psimpl_1_1grammar.html", null ],
        [ "action", "structgemmi_1_1psimpl_1_1action.html", null ],
        [ "action< val_chain_item >", "structgemmi_1_1psimpl_1_1action_3_01val__chain__item_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__chain__item_01_4" ],
        [ "action< val_resn_item >", "structgemmi_1_1psimpl_1_1action_3_01val__resn__item_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__resn__item_01_4" ],
        [ "action< val_name_item >", "structgemmi_1_1psimpl_1_1action_3_01val__name__item_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__name__item_01_4" ],
        [ "action< val_elem_item >", "structgemmi_1_1psimpl_1_1action_3_01val__elem__item_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__elem__item_01_4" ],
        [ "action< rule_chain >", "structgemmi_1_1psimpl_1_1action_3_01rule__chain_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__chain_01_4" ],
        [ "action< rule_resn >", "structgemmi_1_1psimpl_1_1action_3_01rule__resn_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__resn_01_4" ],
        [ "action< rule_name >", "structgemmi_1_1psimpl_1_1action_3_01rule__name_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__name_01_4" ],
        [ "action< rule_elem >", "structgemmi_1_1psimpl_1_1action_3_01rule__elem_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__elem_01_4" ],
        [ "action< val_alt >", "structgemmi_1_1psimpl_1_1action_3_01val__alt_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__alt_01_4" ],
        [ "action< val_resi_single >", "structgemmi_1_1psimpl_1_1action_3_01val__resi__single_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__resi__single_01_4" ],
        [ "action< val_resi_range >", "structgemmi_1_1psimpl_1_1action_3_01val__resi__range_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__resi__range_01_4" ],
        [ "action< val_index_single >", "structgemmi_1_1psimpl_1_1action_3_01val__index__single_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__index__single_01_4" ],
        [ "action< val_index_range >", "structgemmi_1_1psimpl_1_1action_3_01val__index__range_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__index__range_01_4" ],
        [ "action< op_lt >", "structgemmi_1_1psimpl_1_1action_3_01op__lt_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01op__lt_01_4" ],
        [ "action< op_le >", "structgemmi_1_1psimpl_1_1action_3_01op__le_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01op__le_01_4" ],
        [ "action< op_gt >", "structgemmi_1_1psimpl_1_1action_3_01op__gt_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01op__gt_01_4" ],
        [ "action< op_ge >", "structgemmi_1_1psimpl_1_1action_3_01op__ge_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01op__ge_01_4" ],
        [ "action< op_eq >", "structgemmi_1_1psimpl_1_1action_3_01op__eq_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01op__eq_01_4" ],
        [ "action< op_ne >", "structgemmi_1_1psimpl_1_1action_3_01op__ne_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01op__ne_01_4" ],
        [ "action< val_b_compare >", "structgemmi_1_1psimpl_1_1action_3_01val__b__compare_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__b__compare_01_4" ],
        [ "action< val_q_compare >", "structgemmi_1_1psimpl_1_1action_3_01val__q__compare_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01val__q__compare_01_4" ],
        [ "action< rule_hetatm >", "structgemmi_1_1psimpl_1_1action_3_01rule__hetatm_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__hetatm_01_4" ],
        [ "action< rule_polymer >", "structgemmi_1_1psimpl_1_1action_3_01rule__polymer_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__polymer_01_4" ],
        [ "action< rule_solvent >", "structgemmi_1_1psimpl_1_1action_3_01rule__solvent_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__solvent_01_4" ],
        [ "action< rule_water >", "structgemmi_1_1psimpl_1_1action_3_01rule__water_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__water_01_4" ],
        [ "action< rule_hydrogens >", "structgemmi_1_1psimpl_1_1action_3_01rule__hydrogens_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__hydrogens_01_4" ],
        [ "action< rule_backbone >", "structgemmi_1_1psimpl_1_1action_3_01rule__backbone_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__backbone_01_4" ],
        [ "action< rule_sidechain >", "structgemmi_1_1psimpl_1_1action_3_01rule__sidechain_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__sidechain_01_4" ],
        [ "action< rule_all >", "structgemmi_1_1psimpl_1_1action_3_01rule__all_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__all_01_4" ],
        [ "action< rule_not >", "structgemmi_1_1psimpl_1_1action_3_01rule__not_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01rule__not_01_4" ],
        [ "action< and_rest >", "structgemmi_1_1psimpl_1_1action_3_01and__rest_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01and__rest_01_4" ],
        [ "action< or_rest >", "structgemmi_1_1psimpl_1_1action_3_01or__rest_01_4.html", "structgemmi_1_1psimpl_1_1action_3_01or__rest_01_4" ]
      ] ],
      [ "Addends", "structgemmi_1_1Addends.html", "structgemmi_1_1Addends" ],
      [ "ChainNameGenerator", "structgemmi_1_1ChainNameGenerator.html", "structgemmi_1_1ChainNameGenerator" ],
      [ "ComplexCorrelation", "structgemmi_1_1ComplexCorrelation.html", "structgemmi_1_1ComplexCorrelation" ],
      [ "HklValue", "structgemmi_1_1HklValue.html", "structgemmi_1_1HklValue" ],
      [ "ValueSigma", "structgemmi_1_1ValueSigma.html", "structgemmi_1_1ValueSigma" ],
      [ "AsuData", "structgemmi_1_1AsuData.html", "structgemmi_1_1AsuData" ],
      [ "AsuBrick", "structgemmi_1_1AsuBrick.html", "structgemmi_1_1AsuBrick" ],
      [ "MaskedGrid", "structgemmi_1_1MaskedGrid.html", "structgemmi_1_1MaskedGrid" ],
      [ "BesselTables_", "structgemmi_1_1BesselTables__.html", "structgemmi_1_1BesselTables__" ],
      [ "Binner", "structgemmi_1_1Binner.html", "structgemmi_1_1Binner" ],
      [ "Blob", "structgemmi_1_1Blob.html", "structgemmi_1_1Blob" ],
      [ "BlobCriteria", "structgemmi_1_1BlobCriteria.html", "structgemmi_1_1BlobCriteria" ],
      [ "BondIndex", "structgemmi_1_1BondIndex.html", "structgemmi_1_1BondIndex" ],
      [ "C4322", "structgemmi_1_1C4322.html", "structgemmi_1_1C4322" ],
      [ "CustomCoef", "structgemmi_1_1CustomCoef.html", "structgemmi_1_1CustomCoef" ],
      [ "CenterOfMass", "structgemmi_1_1CenterOfMass.html", "structgemmi_1_1CenterOfMass" ],
      [ "Ccp4Base", "structgemmi_1_1Ccp4Base.html", "structgemmi_1_1Ccp4Base" ],
      [ "Ccp4", "structgemmi_1_1Ccp4.html", "structgemmi_1_1Ccp4" ],
      [ "GruberVector", "structgemmi_1_1GruberVector.html", "structgemmi_1_1GruberVector" ],
      [ "SellingVector", "structgemmi_1_1SellingVector.html", "structgemmi_1_1SellingVector" ],
      [ "Restraints", "structgemmi_1_1Restraints.html", "structgemmi_1_1Restraints" ],
      [ "ChemComp", "structgemmi_1_1ChemComp.html", "structgemmi_1_1ChemComp" ],
      [ "CifToMtz", "structgemmi_1_1CifToMtz.html", "structgemmi_1_1CifToMtz" ],
      [ "ContactSearch", "structgemmi_1_1ContactSearch.html", "structgemmi_1_1ContactSearch" ],
      [ "DensityCalculator", "structgemmi_1_1DensityCalculator.html", "structgemmi_1_1DensityCalculator" ],
      [ "DirWalk", "classgemmi_1_1DirWalk.html", "classgemmi_1_1DirWalk" ],
      [ "GlobWalk", "structgemmi_1_1GlobWalk.html", "structgemmi_1_1GlobWalk" ],
      [ "Bridge", "structgemmi_1_1Bridge.html", "structgemmi_1_1Bridge" ],
      [ "HBond", "structgemmi_1_1HBond.html", "structgemmi_1_1HBond" ],
      [ "SecondaryStructureInfo", "structgemmi_1_1SecondaryStructureInfo.html", "structgemmi_1_1SecondaryStructureInfo" ],
      [ "DsspOptions", "structgemmi_1_1DsspOptions.html", "structgemmi_1_1DsspOptions" ],
      [ "DsspCalculator", "structgemmi_1_1DsspCalculator.html", "structgemmi_1_1DsspCalculator" ],
      [ "Element", "structgemmi_1_1Element.html", "structgemmi_1_1Element" ],
      [ "EnerLib", "structgemmi_1_1EnerLib.html", "structgemmi_1_1EnerLib" ],
      [ "needs_fclose", "structgemmi_1_1needs__fclose.html", "structgemmi_1_1needs__fclose" ],
      [ "CharArray", "classgemmi_1_1CharArray.html", "classgemmi_1_1CharArray" ],
      [ "FlatAtom", "structgemmi_1_1FlatAtom.html", "structgemmi_1_1FlatAtom" ],
      [ "FlatStructure", "structgemmi_1_1FlatStructure.html", "structgemmi_1_1FlatStructure" ],
      [ "FloodFill", "structgemmi_1_1FloodFill.html", "structgemmi_1_1FloodFill" ],
      [ "ExpSum", "structgemmi_1_1ExpSum.html", "structgemmi_1_1ExpSum" ],
      [ "ExpSum< N, float >", "structgemmi_1_1ExpSum_3_01N_00_01float_01_4.html", "structgemmi_1_1ExpSum_3_01N_00_01float_01_4" ],
      [ "ExpAnisoSum", "structgemmi_1_1ExpAnisoSum.html", "structgemmi_1_1ExpAnisoSum" ],
      [ "ExpAnisoSum< N, float >", "structgemmi_1_1ExpAnisoSum_3_01N_00_01float_01_4.html", "structgemmi_1_1ExpAnisoSum_3_01N_00_01float_01_4" ],
      [ "GaussianCoef", "structgemmi_1_1GaussianCoef.html", "structgemmi_1_1GaussianCoef" ],
      [ "FPhiProxy", "structgemmi_1_1FPhiProxy.html", "structgemmi_1_1FPhiProxy" ],
      [ "Ofstream", "structgemmi_1_1Ofstream.html", "structgemmi_1_1Ofstream" ],
      [ "Ifstream", "structgemmi_1_1Ifstream.html", "structgemmi_1_1Ifstream" ],
      [ "GridOp", "structgemmi_1_1GridOp.html", "structgemmi_1_1GridOp" ],
      [ "GridMeta", "structgemmi_1_1GridMeta.html", "structgemmi_1_1GridMeta" ],
      [ "GridBase", "structgemmi_1_1GridBase.html", "structgemmi_1_1GridBase" ],
      [ "Grid", "structgemmi_1_1Grid.html", "structgemmi_1_1Grid" ],
      [ "GzStream", "structgemmi_1_1GzStream.html", "structgemmi_1_1GzStream" ],
      [ "MaybeGzipped", "classgemmi_1_1MaybeGzipped.html", "classgemmi_1_1MaybeGzipped" ],
      [ "AnyStream", "structgemmi_1_1AnyStream.html", "structgemmi_1_1AnyStream" ],
      [ "FileStream", "structgemmi_1_1FileStream.html", "structgemmi_1_1FileStream" ],
      [ "MemoryStream", "structgemmi_1_1MemoryStream.html", "structgemmi_1_1MemoryStream" ],
      [ "BasicInput", "classgemmi_1_1BasicInput.html", "classgemmi_1_1BasicInput" ],
      [ "MergingStats", "structgemmi_1_1MergingStats.html", "structgemmi_1_1MergingStats" ],
      [ "Intensities", "structgemmi_1_1Intensities.html", "structgemmi_1_1Intensities" ],
      [ "IntensitiesDataProxy", "structgemmi_1_1IntensitiesDataProxy.html", "structgemmi_1_1IntensitiesDataProxy" ],
      [ "IsoSurface", "structgemmi_1_1IsoSurface.html", "structgemmi_1_1IsoSurface" ],
      [ "IT92", "structgemmi_1_1IT92.html", "structgemmi_1_1IT92" ],
      [ "BidirIterator", "structgemmi_1_1BidirIterator.html", "structgemmi_1_1BidirIterator" ],
      [ "StrideIterPolicy", "classgemmi_1_1StrideIterPolicy.html", "classgemmi_1_1StrideIterPolicy" ],
      [ "IndirectIterPolicy", "classgemmi_1_1IndirectIterPolicy.html", "classgemmi_1_1IndirectIterPolicy" ],
      [ "UniqIterPolicy", "classgemmi_1_1UniqIterPolicy.html", "classgemmi_1_1UniqIterPolicy" ],
      [ "UniqProxy", "structgemmi_1_1UniqProxy.html", "structgemmi_1_1UniqProxy" ],
      [ "ConstUniqProxy", "structgemmi_1_1ConstUniqProxy.html", "structgemmi_1_1ConstUniqProxy" ],
      [ "GroupingIterPolicy", "classgemmi_1_1GroupingIterPolicy.html", "classgemmi_1_1GroupingIterPolicy" ],
      [ "FilterIterPolicy", "classgemmi_1_1FilterIterPolicy.html", "classgemmi_1_1FilterIterPolicy" ],
      [ "FilterProxy", "structgemmi_1_1FilterProxy.html", "structgemmi_1_1FilterProxy" ],
      [ "ConstFilterProxy", "structgemmi_1_1ConstFilterProxy.html", "structgemmi_1_1ConstFilterProxy" ],
      [ "ItemGroup", "structgemmi_1_1ItemGroup.html", "structgemmi_1_1ItemGroup" ],
      [ "LevMar", "structgemmi_1_1LevMar.html", "structgemmi_1_1LevMar" ],
      [ "LinkHunt", "structgemmi_1_1LinkHunt.html", "structgemmi_1_1LinkHunt" ],
      [ "Logger", "structgemmi_1_1Logger.html", "structgemmi_1_1Logger" ],
      [ "Vec3_", "structgemmi_1_1Vec3__.html", "structgemmi_1_1Vec3__" ],
      [ "Mat33", "structgemmi_1_1Mat33.html", "structgemmi_1_1Mat33" ],
      [ "UpperTriangularMat33", "structgemmi_1_1UpperTriangularMat33.html", "structgemmi_1_1UpperTriangularMat33" ],
      [ "SMat33", "structgemmi_1_1SMat33.html", "structgemmi_1_1SMat33" ],
      [ "Transform", "structgemmi_1_1Transform.html", "structgemmi_1_1Transform" ],
      [ "Box", "structgemmi_1_1Box.html", "structgemmi_1_1Box" ],
      [ "SoftwareItem", "structgemmi_1_1SoftwareItem.html", "structgemmi_1_1SoftwareItem" ],
      [ "ReflectionsInfo", "structgemmi_1_1ReflectionsInfo.html", "structgemmi_1_1ReflectionsInfo" ],
      [ "ExperimentInfo", "structgemmi_1_1ExperimentInfo.html", "structgemmi_1_1ExperimentInfo" ],
      [ "DiffractionInfo", "structgemmi_1_1DiffractionInfo.html", "structgemmi_1_1DiffractionInfo" ],
      [ "CrystalInfo", "structgemmi_1_1CrystalInfo.html", "structgemmi_1_1CrystalInfo" ],
      [ "TlsGroup", "structgemmi_1_1TlsGroup.html", "structgemmi_1_1TlsGroup" ],
      [ "BasicRefinementInfo", "structgemmi_1_1BasicRefinementInfo.html", "structgemmi_1_1BasicRefinementInfo" ],
      [ "RefinementInfo", "structgemmi_1_1RefinementInfo.html", "structgemmi_1_1RefinementInfo" ],
      [ "Metadata", "structgemmi_1_1Metadata.html", "structgemmi_1_1Metadata" ],
      [ "Entity", "structgemmi_1_1Entity.html", "structgemmi_1_1Entity" ],
      [ "SiftsUnpResidue", "structgemmi_1_1SiftsUnpResidue.html", "structgemmi_1_1SiftsUnpResidue" ],
      [ "Connection", "structgemmi_1_1Connection.html", "structgemmi_1_1Connection" ],
      [ "CisPep", "structgemmi_1_1CisPep.html", "structgemmi_1_1CisPep" ],
      [ "ModRes", "structgemmi_1_1ModRes.html", "structgemmi_1_1ModRes" ],
      [ "StructSite", "structgemmi_1_1StructSite.html", "structgemmi_1_1StructSite" ],
      [ "Helix", "structgemmi_1_1Helix.html", "structgemmi_1_1Helix" ],
      [ "Sheet", "structgemmi_1_1Sheet.html", "structgemmi_1_1Sheet" ],
      [ "Assembly", "structgemmi_1_1Assembly.html", "structgemmi_1_1Assembly" ],
      [ "PdbReadOptions", "structgemmi_1_1PdbReadOptions.html", "structgemmi_1_1PdbReadOptions" ],
      [ "Atom", "structgemmi_1_1Atom.html", "structgemmi_1_1Atom" ],
      [ "AtomGroup_", "structgemmi_1_1AtomGroup__.html", "structgemmi_1_1AtomGroup__" ],
      [ "Residue", "structgemmi_1_1Residue.html", "structgemmi_1_1Residue" ],
      [ "ConstResidueSpan", "structgemmi_1_1ConstResidueSpan.html", "structgemmi_1_1ConstResidueSpan" ],
      [ "ResidueSpan", "structgemmi_1_1ResidueSpan.html", "structgemmi_1_1ResidueSpan" ],
      [ "ResidueGroup", "structgemmi_1_1ResidueGroup.html", "structgemmi_1_1ResidueGroup" ],
      [ "ConstResidueGroup", "structgemmi_1_1ConstResidueGroup.html", "structgemmi_1_1ConstResidueGroup" ],
      [ "Chain", "structgemmi_1_1Chain.html", "structgemmi_1_1Chain" ],
      [ "const_CRA", "structgemmi_1_1const__CRA.html", "structgemmi_1_1const__CRA" ],
      [ "CRA", "structgemmi_1_1CRA.html", "structgemmi_1_1CRA" ],
      [ "CraIterPolicy", "classgemmi_1_1CraIterPolicy.html", "classgemmi_1_1CraIterPolicy" ],
      [ "CraProxy_", "structgemmi_1_1CraProxy__.html", "structgemmi_1_1CraProxy__" ],
      [ "Model", "structgemmi_1_1Model.html", "structgemmi_1_1Model" ],
      [ "Structure", "structgemmi_1_1Structure.html", "structgemmi_1_1Structure" ],
      [ "ChemLink", "structgemmi_1_1ChemLink.html", "structgemmi_1_1ChemLink" ],
      [ "ChemMod", "structgemmi_1_1ChemMod.html", "structgemmi_1_1ChemMod" ],
      [ "MonLib", "structgemmi_1_1MonLib.html", "structgemmi_1_1MonLib" ],
      [ "UnmergedHklMover", "structgemmi_1_1UnmergedHklMover.html", "structgemmi_1_1UnmergedHklMover" ],
      [ "MtzMetadata", "structgemmi_1_1MtzMetadata.html", "structgemmi_1_1MtzMetadata" ],
      [ "Mtz", "structgemmi_1_1Mtz.html", "structgemmi_1_1Mtz" ],
      [ "MtzDataProxy", "structgemmi_1_1MtzDataProxy.html", "structgemmi_1_1MtzDataProxy" ],
      [ "MtzExternalDataProxy", "structgemmi_1_1MtzExternalDataProxy.html", "structgemmi_1_1MtzExternalDataProxy" ],
      [ "MtzToCif", "classgemmi_1_1MtzToCif.html", "classgemmi_1_1MtzToCif" ],
      [ "NeighborSearch", "structgemmi_1_1NeighborSearch.html", "structgemmi_1_1NeighborSearch" ],
      [ "ZeroCoef", "structgemmi_1_1ZeroCoef.html", "structgemmi_1_1ZeroCoef" ],
      [ "Neutron92", "structgemmi_1_1Neutron92.html", "structgemmi_1_1Neutron92" ],
      [ "FastaSeq", "structgemmi_1_1FastaSeq.html", "structgemmi_1_1FastaSeq" ],
      [ "AtomNameElement", "structgemmi_1_1AtomNameElement.html", "structgemmi_1_1AtomNameElement" ],
      [ "SupResult", "structgemmi_1_1SupResult.html", "structgemmi_1_1SupResult" ],
      [ "ReciprocalGrid", "structgemmi_1_1ReciprocalGrid.html", "structgemmi_1_1ReciprocalGrid" ],
      [ "ReflnBlock", "structgemmi_1_1ReflnBlock.html", "structgemmi_1_1ReflnBlock" ],
      [ "ReflnDataProxy", "structgemmi_1_1ReflnDataProxy.html", "structgemmi_1_1ReflnDataProxy" ],
      [ "ResidueInfo", "structgemmi_1_1ResidueInfo.html", "structgemmi_1_1ResidueInfo" ],
      [ "Scaling", "structgemmi_1_1Scaling.html", "structgemmi_1_1Scaling" ],
      [ "Selection", "structgemmi_1_1Selection.html", "structgemmi_1_1Selection" ],
      [ "AlignmentScoring", "structgemmi_1_1AlignmentScoring.html", "structgemmi_1_1AlignmentScoring" ],
      [ "AlignmentResult", "structgemmi_1_1AlignmentResult.html", "structgemmi_1_1AlignmentResult" ],
      [ "OptionalInt", "structgemmi_1_1OptionalInt.html", "structgemmi_1_1OptionalInt" ],
      [ "SeqId", "structgemmi_1_1SeqId.html", "structgemmi_1_1SeqId" ],
      [ "ResidueId", "structgemmi_1_1ResidueId.html", "structgemmi_1_1ResidueId" ],
      [ "AtomAddress", "structgemmi_1_1AtomAddress.html", "structgemmi_1_1AtomAddress" ],
      [ "StructureFactorCalculator", "classgemmi_1_1StructureFactorCalculator.html", "classgemmi_1_1StructureFactorCalculator" ],
      [ "SmallStructure", "structgemmi_1_1SmallStructure.html", "structgemmi_1_1SmallStructure" ],
      [ "SolventMasker", "structgemmi_1_1SolventMasker.html", "structgemmi_1_1SolventMasker" ],
      [ "NodeInfo", "structgemmi_1_1NodeInfo.html", "structgemmi_1_1NodeInfo" ],
      [ "MutableVectorSpan", "structgemmi_1_1MutableVectorSpan.html", "structgemmi_1_1MutableVectorSpan" ],
      [ "Span", "structgemmi_1_1Span.html", "structgemmi_1_1Span" ],
      [ "Variance", "structgemmi_1_1Variance.html", "structgemmi_1_1Variance" ],
      [ "Covariance", "structgemmi_1_1Covariance.html", "structgemmi_1_1Covariance" ],
      [ "Correlation", "structgemmi_1_1Correlation.html", "structgemmi_1_1Correlation" ],
      [ "DataStats", "structgemmi_1_1DataStats.html", "structgemmi_1_1DataStats" ],
      [ "Op", "structgemmi_1_1Op.html", "structgemmi_1_1Op" ],
      [ "GroupOps", "structgemmi_1_1GroupOps.html", "structgemmi_1_1GroupOps" ],
      [ "SpaceGroup", "structgemmi_1_1SpaceGroup.html", "structgemmi_1_1SpaceGroup" ],
      [ "SpaceGroupAltName", "structgemmi_1_1SpaceGroupAltName.html", "structgemmi_1_1SpaceGroupAltName" ],
      [ "spacegroup_tables", "structgemmi_1_1spacegroup__tables.html", "structgemmi_1_1spacegroup__tables" ],
      [ "ReciprocalAsu", "structgemmi_1_1ReciprocalAsu.html", "structgemmi_1_1ReciprocalAsu" ],
      [ "MmcifOutputGroups", "structgemmi_1_1MmcifOutputGroups.html", "structgemmi_1_1MmcifOutputGroups" ],
      [ "PdbWriteOptions", "structgemmi_1_1PdbWriteOptions.html", "structgemmi_1_1PdbWriteOptions" ],
      [ "Topo", "structgemmi_1_1Topo.html", "structgemmi_1_1Topo" ],
      [ "Position", "structgemmi_1_1Position.html", "structgemmi_1_1Position" ],
      [ "Fractional", "structgemmi_1_1Fractional.html", "structgemmi_1_1Fractional" ],
      [ "NearestImage", "structgemmi_1_1NearestImage.html", "structgemmi_1_1NearestImage" ],
      [ "FTransform", "structgemmi_1_1FTransform.html", "structgemmi_1_1FTransform" ],
      [ "NcsOp", "structgemmi_1_1NcsOp.html", "structgemmi_1_1NcsOp" ],
      [ "MillerHash", "structgemmi_1_1MillerHash.html", "structgemmi_1_1MillerHash" ],
      [ "UnitCellParameters", "structgemmi_1_1UnitCellParameters.html", "structgemmi_1_1UnitCellParameters" ],
      [ "UnitCell", "structgemmi_1_1UnitCell.html", "structgemmi_1_1UnitCell" ],
      [ "XdsAsciiMetadata", "structgemmi_1_1XdsAsciiMetadata.html", "structgemmi_1_1XdsAsciiMetadata" ],
      [ "XdsAscii", "structgemmi_1_1XdsAscii.html", "structgemmi_1_1XdsAscii" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< gemmi::ResidueId >", "structstd_1_1hash_3_01gemmi_1_1ResidueId_01_4.html", "structstd_1_1hash_3_01gemmi_1_1ResidueId_01_4" ],
      [ "hash< gemmi::Op >", "structstd_1_1hash_3_01gemmi_1_1Op_01_4.html", "structstd_1_1hash_3_01gemmi_1_1Op_01_4" ]
    ] ],
    [ "float16_type", "structfloat16__type.html", "structfloat16__type" ]
];