name: CI

on: [push, pull_request]

jobs:
  standard:
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            build: Release
            cc: gcc-4.8
            cxx: g++-4.8
          - os: ubuntu-20.04
            build: Debug
            cc: gcc
            cxx: g++
          - os: macos-10.15
            cc: clang
            cxx: clang++
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.build }} --target all check

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C ${{ matrix.build }}
