name: CI

on: [push, pull_request]

jobs:
  standard:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            build: Debug
          - os: macos-10.15
            build: Release
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: mkdir build
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.build }}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.build }} --target check


  clang35:
    name: "Ubuntu 16.04, Clang 3.5"
    runs-on: ubuntu-16.04
    env:
      CC: clang-3.5
      CXX: clang++-3.5
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libz-dev python3-pip clang-3.5 python3-setuptools
    - run: |
        mkdir build
        cd build
        cmake --version
        cmake .. -DCMAKE_CXX_STANDARD=11
        $CXX --version
        make -j2 all
        make -j2 check
    - run: python3 setup.py install --user --prefix=
    - run: python3 -m unittest discover -v -s tests/


  centos:
    runs-on: ubuntu-latest
    name: "CentOS 7"
    container: centos:7
    steps:
    - uses: actions/checkout@v2
    - run: yum update -y && yum install -y epel-release
    - run: yum install -y gcc-c++ cmake3 make git
    - run: cmake3 .
    - run: make -j2
    - run: make -j2 check
